# ref https://raw.githubusercontent.com/nais/naiserator/master/examples/nais-max.yaml
apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: veilarbportefolje
  namespace: default
  labels:
    team: pto
spec:
  image: docker.pkg.github.com/navikt/veilarbportefolje/veilarbportefolje:{{version}}
  replicas:
    min: 6
    max: 6
    cpuThresholdPercentage: 50
  port: 8080
  ingresses:
    - https://veilarbportefolje.nais.adeo.no
    - https://app.adeo.no/veilarbportefolje
  webproxy: true
  vault:
    enabled: true
    paths:
      - kvPath: /serviceuser/data/prod/srvveilarbportefolje
        mountPath: /var/run/secrets/nais.io/service_user
      - kvPath: /oracle/data/prod/creds/veilarbportefolje-user
        mountPath: /var/run/secrets/nais.io/oracle_creds
      - kvPath: /kv/prod/fss/veilarbportefolje/default
        mountPath: /var/run/secrets/nais.io/vault
  envFrom:
    - configmap: pto-config
  leaderElection: true
  healthcheck:
    liveness:
      path: veilarbportefolje/internal/isAlive
      initialDelay: 60
      timeout: 10
    readiness:
      path: veilarbportefolje/internal/isReady
      initialDelay: 60
      timeout: 10
  prometheus:
    enabled: true
    path: veilarbportefolje/internal/metrics
  resources:
    limits:
      cpu: "8"
      memory: 4Gi
    requests:
      cpu: "1"
      memory: 3Gi
