# ref https://raw.githubusercontent.com/nais/naiserator/master/examples/nais-max.yaml
apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: veilarbportefolje
  namespace: default
  cluster: prod-fss
  labels:
    branch: master
    team: pto
spec:
  image: docker.pkg.github.com/navikt/veilarbportefolje/veilarbportefolje:{{version}}
  replicas:
    min: 3
    max: 3
    cpuThresholdPercentage: 50
  port: 8080
  ingresses:
    - https://veilarbportefolje.nais.adeo.no
    - https://app.adeo.no/veilarbportefolje
  webproxy: true
  vault:
    enabled: true
  leaderElection: true
  healthcheck:
    liveness:
      path: veilarbportefolje/internal/isAlive
      initialDelay: 60
      timeout: 10
    readiness:
      path: veilarbportefolje/internal/isReady
      initialDelay: 60
      timeout: 10
  prometheus:
    enabled: true
    path: veilarbportefolje/internal/metrics
  resources:
    limits:
      cpu: "6"
      memory: 3Gi
    requests:
      cpu: 500m
      memory: 2Gi
  env:
    - APPDYNAMICS_CONTROLLER_HOST_NAME
    - APPDYNAMICS_AGENT_ACCOUNT_NAME
    - APPDYNAMICS_CONTROLLER_PORT
    - APPDYNAMICS_CONTROLLER_SSL_ENABLED
    - SECURITY_TOKEN_SERVICE_OPENID_CONFIGURATION_URL
    - VEILARBAKTIVITETAPI_URL
    - VEILARBDIALOGAPI_URL
    - VEILARBOPPFOLGINGAPI_URL
    - VEILARBVEILEDERAPI_URL
    - VIRKSOMHET_DIGITALKONTAKINFORMASJON_V1_ENDPOINTURL
    - VIRKSOMHET_DIGITALKONTAKINFORMASJON_V1_SECURITYTOKEN
    - VIRKSOMHET_DIGITALKONTAKINFORMASJON_V1_WSDLURL
    - VIRKSOMHET_ENHET_V1_ENDPOINTURL
    - VIRKSOMHET_ENHET_V1_SECURITYTOKEN
    - VIRKSOMHET_ENHET_V1_WSDLURL
    - VEILARBPORTEFOLJEDB_URL
    - VEILARBPORTEFOLJEDB_ONSHOSTS
