CREATE TABLE BRUKER_PROFILERING_V2
(
    FNR                   VARCHAR(11) NOT NULL,
    PERIODEID             UUID,
    PROFILERING_RESULTAT  VARCHAR(40),
    PROFILERING_TIDSPUNKT TIMESTAMP,

    PRIMARY KEY (FNR, PERIODEID)
);

CREATE TABLE SISTE_ARBEIDSSOKER_PERIODE
(
    ARBEIDSSOKER_PERIODE_ID UUID,
    FNR                     VARCHAR(11) NOT NULL,

    PRIMARY KEY (FNR)
);
