apiVersion: unleash.nais.io/v1
kind: ApiToken
metadata:
  name: veilarbportefolje
  namespace: pto
  cluster: dev-fss
  labels:
    team: pto
spec:
  unleashInstance:
    apiVersion: unleash.nais.io/v1
    kind: RemoteUnleash
    name: team-obo
  secretName: veilarbportefolje-unleash-api-token

  environment: development
