name: Scan and report Docker image vulnerabilities

env:
  IMAGE: ghcr.io/${{ github.repository }}/veilarbportefolje
  IMAGE_TAG: ${{ github.sha }}

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  security-events: write

jobs:
  build-and-scan-docker-image:
    name: Build and scan Docker image
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'

      - name: Build maven artifacts
        run: mvn -Dgithub.token=${{ secrets.GITHUB_TOKEN }} -B package -D skipTests

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: ${{ env.IMAGE }}:${{ env.IMAGE_TAG }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ env.IMAGE }}:${{ env.IMAGE_TAG }}'
          format: 'sarif'
          output: 'trivy.sarif'
          severity: 'CRITICAL,HIGH'
          limit-severities-for-sarif: true

      - name: Upload results to GitHub Security
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy.sarif'